jobs:
  build-macos-clang:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: compile
      run: 'cd cpp

        mkdir bits

        echo $''#include <vector>\n#include <set>\n#include <map>\n#include <unordered_set>\n#include
        <unordered_map>\n#include <queue>\n#include <deque>\n#include <stack>\n#include
        <iostream>\n#include <iomanip>\n#include <complex>\n#include <cassert>\n#include
        <random>\n#include <chrono>\n#include <functional>\n#include <array>\n#include
        <bitset>\n#include <numeric>\n'' > bits/stdc++.h

        find . -name ''*.cpp'' -print0 | xargs -n1 -0 clang++ ${{ matrix.config.compiler-options
        }} .

        '
    strategy:
      matrix:
        config:
        - compiler-options: -Wall -Wextra -std=c++2b -isystem
        - compiler-options: -Wall -Wextra -Wno-sign-compare -std=c++2b -isystem
  build-ubuntu-clang:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: install clang
      run: 'sudo apt-key adv --fetch-keys https://apt.llvm.org/llvm-snapshot.gpg.key

        sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17
        main"

        sudo apt-get install clang-17

        '
    - continue-on-error: true
      name: compile
      run: 'cd cpp

        find . -name ''*.cpp'' -print0 | xargs -n1 -0 clang++-17 -Wall -Wextra -std=c++2b

        '
  build-ubuntu-gcc-13:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: install g++
      run: 'sudo add-apt-repository ppa:ubuntu-toolchain-r/test

        sudo apt-get install g++-13

        '
    - continue-on-error: true
      name: compile
      run: 'cd cpp

        find . -name ''*.cpp'' -print0 | xargs -n1 -0 g++-13 ${{ matrix.config.compiler-options
        }}

        '
    strategy:
      matrix:
        config:
        - compiler-options: -Wall -Wextra -std=c++20
        - compiler-options: -Wall -Wextra -Wno-sign-compare -std=c++23
        - compiler-options: -fanalyzer -Wno-analyzer-null-dereference -std=c++23
  build-windows-visual-cpp-17:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: compile
      run: 'call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"

        cd cpp

        mkdir bits

        C:\msys64\usr\bin\echo.exe -e ''#include \74vector\76\n#include \74set\76\n#include
        \74map\76\n#include \74unordered_set\76\n#include \74unordered_map\76\n#include
        \74queue\76\n#include \74deque\76\n#include \74stack\76\n#include \74iostream\76\n#include
        \74iomanip\76\n#include \74complex\76\n#include \74cassert\76\n#include \74random\76\n#include
        \74chrono\76\n#include \74functional\76\n#include \74array\76\n#include \74bitset\76\n#include
        \74numeric\76\n'' > bits\stdc++.h

        C:\msys64\usr\bin\find . -name ''*.cpp'' -print0 | C:\msys64\usr\bin\xargs
        -n1 -0 cl //std:c++17 //EHsc //I .

        '
      shell: cmd
  build-windows-visual-cpp-20:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: compile
      run: 'call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"

        cd cpp

        mkdir bits

        C:\msys64\usr\bin\echo.exe -e ''#include \74vector\76\n#include \74set\76\n#include
        \74map\76\n#include \74unordered_set\76\n#include \74unordered_map\76\n#include
        \74queue\76\n#include \74deque\76\n#include \74stack\76\n#include \74iostream\76\n#include
        \74iomanip\76\n#include \74complex\76\n#include \74cassert\76\n#include \74random\76\n#include
        \74chrono\76\n#include \74functional\76\n#include \74array\76\n#include \74bitset\76\n#include
        \74numeric\76\n'' > bits\stdc++.h

        C:\msys64\usr\bin\find . -name ''*.cpp'' -print0 | C:\msys64\usr\bin\xargs
        -n1 -0 cl //std:c++20 //EHsc //I .

        '
      shell: cmd
name: C++ CI
on:
  repository_dispatch:
    types: trigger-ga___cpp.yml
