jobs:
  build-ubuntu-rustc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: install rustc
      run: 'sudo apt install rustc

        '
    - continue-on-error: true
      name: compile
      run: 'cd rust

        cargo build

        '
name: Rust CI
on:
  repository_dispatch:
    types: trigger-ga___rust.yml
